### ISSUE TITLE
ONNX GraphSurgeon is not available on aarch64 platforms

### ISSUE THREAD

**Issue by leimao** [NVIDIA/Deep-Learning-Accelerator-SW#7]
ONNX GraphSurgeon is not available on aarch64 platforms and therefore the [requirement](https://github.com/NVIDIA/Deep-Learning-Accelerator-SW/blob/b290d4df6360895d2d4ef9377b32434adb180186/requirements.txt) installation is not completely successful on Xavier/Orin.

**Comment by nvoliver** [comment]
Thanks, we will clarify in the next update that the Python scripts are intended to be run on host.

**Comment by leimao** [comment]
> Thanks, we will clarify in the next update that the Python scripts are intended to be run on host.

Thanks @nvoliver. In fact, I download the source code of ONNX GraphSurgeon, built it on aarch64 platforms, and it just worked fine. You may just request the TensorRT team to release ONNX GraphSurgeon for aarch64 platforms starting from the next release, which should be something straightforward to do.

**Comment by nvoliver** [comment]
Updated the instructions in #8.
